[package]
name = "substrate-codec-derive"
description = "Serialization and deserialization derive macro"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
proc-macro = true

[dependencies]
substrate-codec = { path = "../" }
syn = "0.14"
quote = "0.6"
proc-macro2 = "0.4"

[features]
default = ["std"]
std = ["substrate-codec/std"]
